username = input('Имя пользователя')
title = input('Заголовок заметки:')
content = input('Описание заметки:')
status = input('Статус заметки')
created_date = input('Дата создания заметки:')
issue_date = input('Дата истечения заметки:')
print('Имя пользователя:',username)
print('Заголовок заметки:',title)
print('Описание заметки:',content )
print('Статус заметки:',status)
print('Дата создания заметки:',created_date)
print('Дата истечения заметки:',issue_date)
